export enum COA {
    CanViewAccounts = "CanViewAccounts"
    , CanViewCOA = "CanViewCOA"
    , CanViewMainHead = "CanViewMainHead"
    , CanViewHeadCategory = "CanViewHeadCategory"
    , CanViewSubCategory = "CanViewSubCategory"
    , CanViewPostingAccount = "CanViewPostingAccount"
    , CanViewCOATree = "CanViewCOATree"
    , CanAddHeadCategory = "CanAddHeadCategory"
    , CanEditHeadCategory = "CanEditHeadCategory"
    , CanDeleteHeadCategory = "CanDeleteHeadCategory"
    , CanAddSubCategory = "CanAddSubCategory"
    , CanEditSubCategory = "CanEditSubCategory"
    , CanDeleteSubCategory = "CanDeleteSubCategory"
    , CanAddPostingAccount = "CanAddPostingAccount"
    , CanEditPostingAccount = "CanEditPostingAccount"
    , CanDeletePostingAccount = "CanDeletePostingAccount"
    , CanPrintCOATree = "CanPrintCOATree"
}

export enum Dashboard {
    CanAccessDashboard = " CanAccessDashboard"
    , CavViewRecentTransaction = " CavViewRecentTransaction"
    , CanViewFinancialSummary = " CanViewFinancialSummary"
}

export enum Voucher {
    CanViewVoucher = "CanViewVoucher"
    , CanAddVoucher = "CanAddVoucher"
    , CanEditVoucher = "CanEditVoucher"
    , CanDeleteVoucher = "CanDeleteVoucher"
    , CanPostVoucher = "CanPostVoucher"
    , CanPrintVoucher = "CanPrintVoucher"
}

export enum Can_View_Role {
    CanViewRole = "CanViewRole"
    , CanAddRole = "CanAddRole"
    , CanEditRole = "CanEditRole"
    , CanManageRoleRights = "CanManageRoleRights"
}

export enum Can_View_Users {
    CanViewUsers = "CanViewUsers"
    , CanAddUsers = "CanAddUsers"
    , CanEditUsers = "CanEditUsers"
    , CanDeleteUsers = "CanDeleteUsers"
    , CanManageUserRights = "CanManageUserRights"
    , CanUpdatePassword = "CanUpdatePassword"
}

export enum Reports {
    CanViewAccountReports = "CanViewAccountReports"
    , CanViewFinancialReports = "CanViewFinancialReports"
    , CanViewLedgerReports = "CanViewLedgerReports"
    , CanViewTrialBalance = "CanViewTrialBalance"
    , CanViewProfitLossReport = "CanViewProfitLossReport"
    , CanViewBalanceSheetReport = "CanViewBalanceSheetReport"
    , CanViewTransactionReports = "CanViewTransactionReports"
    , CanViewDailyTransaction = "CanViewDailyTransaction"
    , CanViewPaymentReceipt = "CanViewPaymentReceipt"
}

export enum MainMenuRights {
    CanViewVoucher = "CanViewVoucher"
    , CanAccessDashboard = " CanAccessDashboard"
    , CanViewAccounts = "CanViewAccounts"
    , CanViewCOA = "CanViewCOA"
    , CanViewAccountReports = "CanViewAccountReports"
    , CanViewRole = "CanViewRole"
    , CanViewUsers = "CanViewUsers"
    , CanViewPayroll = "CanViewPayroll"
    , CanViewEmployee = "CanViewEmployee"
    , CanManageAttendance = "CanManageAttendance"
    , CanViewOvertime = "CanViewOvertime"
    , CanManagePayroll = "CanManagePayroll"
    , CanViewSalarySheet = "CanViewSalarySheet"
    , CanViewPayrollReport = "CanViewPayrollReport"
    , CanViewInventory = "CanViewInventory"
    , CanViewStockManagement = "CanViewStockManagement"
    , CanViewPreRequisite = "CanViewPreRequisite"
    , CanViewItemOpening = "CanViewItemOpening"
    , CanViewInventoryReports = "CanViewInventoryReports"
    , CanViewPurchaseOrder = "CanViewPurchaseOrder"
    , CanViewPurchaseInvoice = "CanViewPurchaseInvoice"
    , CanViewPurchaseReturn = "CanViewPurchaseReturn"
    , CanViewIssuance = "CanViewIssuance"
    , CanViewIssuanceReturn = "CanViewIssuanceReturn"
    , CanViewStockManagementReports = "CanViewStockManagementReports"
    , CanViewAdministrator = "CanViewAdministrator"
    , CanViewVendors = "CanViewVendors"
    , CanViewCustomers = "CanViewCustomers"
    , CanViewOthers = "CanViewOthers"
    , CanViewProduction = "CanViewProduction"
    , CanViewProdPreRequisite = "CanViewProdPreRequisite"
    , CanViewProdOrder = "CanViewProdOrder"
}

export enum Payroll {
    CanViewPayroll = "CanViewPayroll"
    , CanViewEmployee = "CanViewEmployee"
    , CanAddEmployee = "CanAddEmployee"
    , CanEditEmployee = "CanEditEmployee"
    , CanDeleteEmployee = "CanDeleteEmployee"
    , CanManagePayroll = "CanManagePayroll"
    , CanManageAttendance = "CanManageAttendance"
    , CanEditAttendanceStatus = "CanEditAttendanceStatus"
    , CanEditAttendanceTime = "CanEditAttendanceTime"
    , CanViewDepartment = "CanViewDepartment"
    , CanAddDepartment = "CanAddDepartment"
    , CanEditDepartment = "CanEditDepartment"
    , CanDeleteDepartment = "CanDeleteDepartment"
    , CanViewDesignation = "CanViewDesignation"
    , CanAddDesignation = "CanAddDesignation"
    , CanEditDesignation = "CanEditDesignation"
    , CanDeleteDesignation = "CanDeleteDesignation"
    , CanViewBenefitType = "CanViewBenefitType"
    , CanAddBenefitType = "CanAddBenefitType"
    , CanEditBenefitType = "CanEditBenefitType"
    , CanDeleteBenefitType = "CanDeleteBenefitType"
    , CanViewLoanType = "CanViewLoanType"
    , CanAddLoanType = "CanAddLoanType"
    , CanEditLoanType = "CanEditLoanType"
    , CanDeleteLoanType = "CanDeleteLoanType"

    , GenerateSalarySheet = "GenerateSalarySheet"
    , SaveSalarySheet = "SaveSalarySheet"
    , PrintSalarySheet = "PrintSalarySheet"
}

export enum PayrollReports {
    CanViewEmployeeReport = "CanViewEmployeeReport"
    , CanViewAttendanceReport = "CanViewAttendanceReport"
    , CanViewOvertimeReport = "CanViewOvertimeReport"
    , CanViewAttendanceRegisterReport = "CanViewAttendanceRegisterReport"
}

export enum InventoryRights {
    CanViewInventory = "CanViewInventory"
    , CanViewPreRequisite = "CanViewPreRequisite"
    , CanAddItemType = "CanAddItemType"
    , CanAddItemCategory = "CanAddItemCategory"
    , CanAddUnit = "CanAddUnit"
    , CanAddItem = "CanAddItem"
    , CanAddBundle = "CanAddBundle"
    , CanViewItemOpening = "CanViewItemOpening"
    , CanAddItemOpening = "CanAddItemOpening"
    , CanUpdateItemOpening = "CanUpdateItemOpening"
    , CanDeleteItemOpening = "CanDeleteItemOpening"
    , CanShowPurchaseInvoicePrice = "CanShowPurchaseInvoicePrice"
    //reports
    , CanViewInventoryReports = "CanViewInventoryReports"
    , CanViewItemReport = "CanViewItemReport"
}

export enum StockManagementRights {
    CanViewStockManagement = "CanViewStockManagement"
    , CanViewPurchaseOrder = "CanViewPurchaseOrder"
    , CanAddPurchaseOrder = "CanAddPurchaseOrder"
    , CanUpdatePurchaseOrder = "CanUpdatePurchaseOrder"
    , CanDeletePurchaseOrder = "CanDeletePurchaseOrder"
    , CanPostPurchaseOrder = "CanPostPurchaseOrder"
    , CanViewPurchaseInvoice = "CanViewPurchaseInvoice"
    , CanAddPurchaseInvoice = "CanAddPurchaseInvoice"
    , CanUpdatePurchaseInvoice = "CanUpdatePurchaseInvoice"
    , CanDeletePurchaseInvoice = "CanDeletePurchaseInvoice"
    , CanPostPurchaseInvoice = "CanPostPurchaseInvoice"
    , CanShowPurchaseInvoicePrice = "CanShowPurchaseInvoicePrice"
    , CanViewPurchaseReturn = "CanViewPurchaseReturn"
    , CanAddPurchaseReturn = "CanAddPurchaseReturn"
    , CanUpdatePurchaseReturn = "CanUpdatePurchaseReturn"
    , CanDeletePurchaseReturn = "CanDeletePurchaseReturn"
    , CanPostPurchaseReturn = "CanPostPurchaseReturn"
    , CanViewIssuance = "CanViewIssuance"
    , CanAddIssuance = "CanAddIssuance"
    , CanUpdateIssuance = "CanUpdateIssuance"
    , CanDeleteIssuance = "CanDeleteIssuance"
    , CanPostIssuance = "CanPostIssuance"
    , CanViewIssuanceReturn = "CanViewIssuanceReturn"
    , CanAddIssuanceReturn = "CanAddIssuanceReturn"
    , CanUpdateIssuanceReturn = "CanUpdateIssuanceReturn"
    , CanDeleteIssuanceReturn = "CanDeleteIssuanceReturn"
    , CanPostIssuanceReturn = "CanPostIssuanceReturn"
    // reports
    , CanViewStockManagementReports = "CanViewStockManagementReports"
    , CanViewItemLedgerReport = "CanViewItemLedgerReport"
    , CanViewStockDailyTransactionReport = "CanViewStockDailyTransactionReport"
    , CanViewStockSummaryReport = "CanViewStockSummaryReport"
}

export enum AdministratorRights {
    CanViewAdministrator = "CanViewAdministrator"
    , CanViewVendors = "CanViewVendors"
    , CanViewCustomers = "CanViewCustomers"
    , CanViewOthers = "CanViewOthers"
    , CanAddVendors = "CanAddVendors"
    , CanUpdateVendors = "CanUpdateVendors"
    , CanDeleteVendors = "CanDeleteVendors"
    , CanAddCustomers = "CanAddCustomers"
    , CanUpdateCustomers = "CanUpdateCustomers"
    , CanDeleteCustomers = "CanDeleteCustomers"
    , CanAddOthers = "CanAddOthers"
    , CanUpdateOthers = "CanUpdateOthers"
    , CanDeleteOthers = "CanDeleteOthers"
}

export enum ProductionRights {
    CanViewProduction = "CanViewProduction"
    , CanViewProdPreRequisite = "CanViewProdPreRequisite"
    , CanViewProdOrder = "CanViewProdOrder"
    , CanAddProductCategory = "CanAddProductCategory"
    , CanAddProduct = "CanAddProduct"
    , CanAddProdOrder = "CanAddProdOrder"
    , CanUpdateProdOrder = "CanUpdateProdOrder"
    , CanDeleteProdOrder = "CanDeleteProdOrder"
    , CanPostProdOrder = "CanPostProdOrder"
    , CanPrintProdOrder = "CanPrintProdOrder"
}