export enum DATA_STORE_NAME {
    AUTHSTORE = 'AUTHSTORE'
    , AREA = 'AREA'
    , COUNTRIES = 'COUNTRIES'
    , ORGANIZATIONPROFILE = 'ORGANIZATIONPROFILE'
    , ORGANIZATIONLOGOS = 'ORGANIZATIONLOGOS'
    , QUALIFICATION = 'QUALIFICATION'
    , YEARS = 'YEARS'
    , STATE = 'STATE'
    , RELIGION = 'RELIGION'
    , OCCUPATION = 'OCCUPATION'
    , DEFAULTCLASSES = 'DEFAULTCLASSES'
    , CITIES = 'CITIES'
    , CLASSES = 'CLASSES'
    , SUBJECTS = 'SUBJECTS'
    , CLASSSUBJECTS = 'CLASSSUBJECTS'
    , CLASSSECTION = 'CLASSSECTION'
    , ORGANIZATIONOUTLETS = 'ORGANIZATIONOUTLETS'
    , TYPENAME = 'TYPENAME'
    , STUDENTOVERDUESUMMARY = 'STUDENTOVERDUESUMMARY'
    , CASTE = 'CASTE'
    , STUDENTFEESUMMARY = 'STUDENTFEESUMMARY'
    , ACTIVESTUDENT = "ACTIVESTUDENT"
    , INACTIVESTUDENT = "INACTIVESTUDENT"
    , FEEDISCOUNTREASON = "FEEDISCOUNTREASON"
    , MOI = "MOI"
    , OVERDUETYPES = "OVERDUETYPES"
    , SESSIONS = "SESSIONS"
    , SESSIONSMONTHS = "SESSIONSMONTHS"
    , OVERDUESTATUS = "OVERDUESTATUS"
    , DASHBOARDCOUNT = "DASHBOARDCOUNT"
    , MONTHS = "MONTHS"
    , STUDENTATTENDANCE = "STUDENTATTENDANCE"
    , EMPLOYEEATTENDANCE = "EMPLOYEEATTENDANCE"
    , USERS = "USERS"
    , TABBING = 'TABBING'
    , USERRIGHTS = 'USERRIGHTS'
    , COMMUNICATION = "COMMUNICATION"
    , DEPARTMENTS = "DEPARTMENTS"
    , BENEFITS = "BENEFITS"
    , EMPLOYEELOAN = "EMPLOYEELOAN"
    , LOANTYPE = "LOANTYPE"
    , ALLOWANCETYPE = "ALLOWANCETYPE"
    , OFFDAYS = "OFFDAYS"
    , DESIGNATION = "DESIGNATION"

    // Accounts Related Store
    , MAINHEAD = "MAINHEAD"
    , HEADCATEGORY = "HEADCATEGORY"
    , SUBCATEGORY = "SUBCATEGORY"
    , POSTINGACCOUNTS = "POSTINGACCOUNTS"
    , ACCOUNTSLEDGER = "ACCOUNTSLEDGER"
    , VOUCHER = "VOUCHER"
    , HEADCATEGORYREPORT = "HEADCATEGORYREPORT"
    , MAINHEADREPORTS = "MAINHEADREPORTS"
    , SUBCATEGORYREPORTS = "SUBCATEGORYREPORTS"
    , CONFIGURATIONSETTING = "CONFIGURATIONSETTING"
    , DASHBOARDOUTLETS = "DASHBOARDOUTLETS"
    , PERSON = "PERSON"

    // Inventory  Stores
    , ItemTYPE = "ItemTYPE"
    , BUNDLE = "BUNDLE"
    , UNITS = "UNITS"
    , ITEMS = "ITEMS"
    , ITEMCATEGORY = "ITEMCATEGORY"
    , ITEMVENDOR = "ITEMVENDOR"
    , BRANDS = "BRANDS"
    , PARTICULAR = "PARTICULAR"

    //Invoices Store
    , PURCHASEINVOICE = "PURCHASEINVOICE"
    , SALEINVOICE = "SALEINVOICE"
    , ISSUANCEINVOICE = "ISSUANCEINVOICE"


    // Employee Store

    , EMPLOYEE_DEPARTMENT = "EMPLOYEE_DEPARTMENT"
    , BENEFIT_TYPE = "BENEFIT_TYPE"
    , DESIGNATION_TYPE = "DESIGNATION_TYPE"
    , LOAN_TYPE = "LOAN_TYPE"
    , EMPLOYEE = "EMPLOYEE"
    , ALLOWANCE_TYPE = "ALLOWANCE_TYPE"

}

export enum UI_STORE_NAME {
    UI_ACCOUNTLEDGERREPORTS = "UI_ACCOUNTLEDGERREPORTS"
    , UI_SUBCATEGORYREPORTS = "UI_SUBCATEGORYREPORTS"
    , UI_HEADCATEGORYREPORTS = "UI_HEADCATEGORYREPORTS"
    , UI_MAINHEADREPORTS = "UI_MAINHEADREPORTS"
    , UI_CHARTOFACCOUNT = "UI_CHARTOFACCOUNT"
    , UI_INVENTORY = "UI_INVENTORY"
    , UI_VOUCHER = "UI_VOUCHER"
    //Invoices UI Store     
    , UI_PURCHASEINVOICE = "UI_PURCHASEINVOICE"
    , UI_SALEINVOICE = "=UI_SALEINVOICE"
    , UI_ISSUANCEINVOICE = "=UI_ISSUANCEINVOICE"
}